### PR TITLE
 Part3 ideas

### PR DESCRIPTION
**Pull request by Nowosad**

### CODE REVIEW

**Comment by Nowosad** [comment]
Hey @Robinlovelace @jannes-m - as you work on the last things from https://github.com/Robinlovelace/geocompr/issues/137, my plan is to gather and organize ideas for chapters in the third part of the book. I'm not going to build them until the second part will be sent to reviewers.

**Comment by Robinlovelace** [comment]
This sounds great Jakub - will check it out and start thinking about part 3 while finalizing those last issues.

**Comment by jannes-m** [comment]
Keep also in mind:
- https://github.com/Robinlovelace/geocompr/blob/master/our-chapters.md
- raster chapter on land-use classification/change detection
- big data/cloud computing

**Comment by Nowosad** [comment]
Yep - our-chapters.md is awesome.

**Pull request merged**
