### PR TITLE
Include frontcover

### PR DESCRIPTION
**Pull request by marcosci**
I included the code in `code` and the cover in `images`.
I also put the console idea of Robin in one of the tiles - opinions?

### CODE REVIEW

**Comment by Nowosad** [comment]
Thanks @marcosci - I am going to merge it now to improve the code style a bit. 
One question - what do you think about removing this vertical line in the Robin's console idea?

**Comment by Robinlovelace** [comment]
Also looking at this.

Note I had errors in 2 places:

```r
r <- raster("images/r_logo.tif")
# and:
  mutate(id = ifelse(r_logo==255, 0, 1)) %>% 
```

**Comment by marcosci** [comment]
@Nowosad sorry for that :yum: and sure, if Robin is fine with that remove it :+1: 

@Robinlovelace what are the errors?

**Comment by Robinlovelace** [comment]
May be because I ran it from different directory. Happy for the line to go. Also suspect it needs to be higher resolution but looking great to me.

**Comment by Nowosad** [comment]
I've cleaned the code a few minutes ago. 
Everything ran well on my laptop.

**Pull request merged**
