### PR TITLE
Mention qgis tag in readme

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @jannes-m, worth merging now or should we wait until the QGIS stuff stabilises?

**Comment by jannes-m** [comment]
HEy Robin,
jep, I tried the docker image. However, running the RQGIS3 tests resulted in multiple errors... Therefore, I would wait with the merge. Anyways, thanks for the effort!

**Comment by Robinlovelace** [comment]
I'll hold my horses :horse:  so to speak! Thanks jannes.

**Comment by Robinlovelace** [comment]
Looking to merge this now.

**Pull request merged**
