### PR TITLE
Replace ggmap with revgeo

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @jannes-m here are the results from this unevaluated chunk - seem reasonable?

``` r
coords = structure(c(10, 13.3889, 7.038, 12.2978, 8.7415, 11.1021, 9.1839, 
11.6117, 53.5457, 52.5091, 51.2723, 51.3662, 50.1232, 49.4055, 
48.7784, 48.1397), .Dim = c(8L, 2L), .Dimnames = list(c("1", 
"2", "3", "4", "5", "6", "7", "8"), c("X", "Y")))
purrr::map_chr(1:nrow(coords), function(i) {
  revgeo::revgeo(coords[i, 1], coords[i, 2])[[1]]
})
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=10&lat=53.5457"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=13.3889&lat=52.5091"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=7.038&lat=51.2723"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=12.2978&lat=51.3662"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=8.7415&lat=50.1232"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=11.1021&lat=49.4055"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=9.1839&lat=48.7784"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=11.6117&lat=48.1397"
#> [1] "11 Ida-Ehre-Platz, Hamburg, Hamburg, 20095, Germany"                                      
#> [2] "House Number Not Found Street Not Found, Berlin, Berlin, 10117, Germany"                  
#> [3] "House Number Not Found Street Not Found, Wülfrath, North Rhine-Westphalia, 42489, Germany"
#> [4] "48 Leipziger Straße, Leipzig, Saxony, 04178, Germany"                                     
#> [5] "22 Street Not Found, Frankfurt am Main, Hesse, 60314, Germany"                            
#> [6] "17 Schnorrstraße, Nuremberg, Bavaria, 90471, Germany"                                     
#> [7] "House Number Not Found Jägerstraße, Stuttgart, Baden-Württemberg, 70174, Germany"         
#> [8] "House Number Not Found Street Not Found, Munich, Bavaria, 81677, Germany"
```

Created on 2018-09-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jannes-m** [comment]
just tried it, seems to work, and since photon is open source in contrast to Google, I tend to like the approach better, and even better it lets you also use all coords at once, i.e. we can get rid off the nasty loop, ok, I am convince, will implement that tomorrow. @Robinlovelace Thanks for making me aware of **revgeo**!!

**Comment by Robinlovelace** [comment]
Thanks for the quickfire feedback @jannes-m.

Here's another test: the results seem good!

``` r
coords = structure(c(10, 13.3889, 7.038, 12.2978, 8.7415, 11.1021, 9.1839, 
11.6117, 53.5457, 52.5091, 51.2723, 51.3662, 50.1232, 49.4055, 
48.7784, 48.1397), .Dim = c(8L, 2L), .Dimnames = list(c("1", 
"2", "3", "4", "5", "6", "7", "8"), c("X", "Y")))
library(tidyverse)
metro_chars = map_chr(1:nrow(coords), function(i) {
  revgeo::revgeo(coords[i, 1], coords[i, 2])[[1]]
})
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=10&lat=53.5457"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=13.3889&lat=52.5091"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=7.038&lat=51.2723"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=12.2978&lat=51.3662"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=8.7415&lat=50.1232"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=11.1021&lat=49.4055"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=9.1839&lat=48.7784"
#> [1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=11.6117&lat=48.1397"
metro_names_new = map_chr(metro_chars, ~stringr::str_split(., pattern = ", ")[[1]][2])
spDataLarge::metro_names$administrative_area_level_2
#> [1] NA              NA              "Düsseldorf"    "Leipzig"      
#> [5] "Darmstadt"     "Mittelfranken" "Stuttgart"     "Oberbayern"
metro_names_new
#> [1] "Hamburg"           "Berlin"            "Wülfrath"         
#> [4] "Leipzig"           "Frankfurt am Main" "Nuremberg"        
#> [7] "Stuttgart"         "Munich"
```

Created on 2018-09-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by Robinlovelace** [comment]
Heads-up: the latest version of the PR seems to work, until it gets to downloading the shops:

```
metro_names
           locality administrative_area_level_1
1           Hamburg                     Hamburg
2            Berlin                      Berlin
3          Wülfrath      North Rhine-Westphalia
4           Leipzig                      Saxony
5 Frankfurt am Main                       Hesse
6         Nuremberg                     Bavaria
7         Stuttgart           Baden-Württemberg
8            Munich                     Bavaria
> shops = map(locality, function(x) {
+   message("Downloading shops of: ", x, "\n")
+   # give the server a bit time
+   Sys.sleep(sample(seq(5, 10, 0.1), 1))
+   query = opq(x) %>%
+     add_osm_feature(key = "shop")
+   points = osmdata_sf(query)
+   # request the same data again if nothing has been downloaded
+   iter = 2
+   while (nrow(points$osm_points) == 0 & iter > 0) {
+     points = osmdata_sf(query)
+     iter = iter - 1
+   }
+   points = st_set_crs(points$osm_points, 4326)
+ })
Downloading shops of: Hamburg

Downloading shops of: Berlin

 Show Traceback
 
 Rerun with Debug
 Error in curl::curl_fetch_memory(url, handle = handle) : 
  Error in the HTTP2 framing layer 
```

**Comment by Robinlovelace** [comment]
Wow: looks like the code can reproduce the locality perfectly:

```
 locality
[1] "Hamburg"           "Berlin"            "Wülfrath"          "Leipzig"           "Frankfurt am Main" "Nuremberg"         "Stuttgart"        
[8] "Munich"           
> spDataLarge::metro_names$locality
[1] "Hamburg"           "Berlin"            "Wülfrath"          "Leipzig"           "Frankfurt am Main" "Nürnberg"          "Stuttgart"        
[8] "München" 
```

Suggestion: merge this PR then re-instate the umlaut modifying code (apologies for removing that, think I see now why that was there).

**Comment by jannes-m** [comment]
Will close the PR since I have updated the text differently while using **revgeo**. It is now much simpler, will let you know in the commit. I have also run the code for downloading the pois/shops with the "new" city names (note that they are now in English), and it worked perfectly fine.

**Comment by Robinlovelace** [comment]
Great, hope the contents of this PR + associated comments were useful!

**Pull request closed without merging**
