### PR TITLE
Remove triple colon...

### PR DESCRIPTION
**Pull request by prosoitos**
...which I think was a typo. Triple colon does exist, but I don't see why it would be necessary here. Apologies if I am wrong.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Something like this (make sense?):

```
**sf** provides a method for the generic `aggregate` function. 
It is activated when an `sf` object is passed to the first `x` argument and the second `by` argument is a list of grouping variables:^[
The `~` notation does not result in `sf` outputs, e.g. with `aggregate(pop ~ continent, sum, data = world)`.
]
```

**Comment by Robinlovelace** [comment]
For more on generics see https://adv-r.hadley.nz/s3.html#s3-methods

**Comment by prosoitos** [comment]
> It was deliberate, but there was a typo in there. The true function is sf:::aggregate.sf().
> Although it is exported, it does not appear because it is a generic method.

Oh, I see. Thank you for the explanations. The package here is (to me at least) somewhat confusing since calling `?sf::aggregate` opens the help file for `aggregate.sf()`, but trying to run, for instance:

```r
world_agg2 = sf::aggregate(world["pop"], by = list(world$continent), FUN = sum, na.rm = TRUE)
```

leads to the `Error: 'aggregate' is not an exported object from 'namespace:sf'` message.

While running:

```r
world_agg2 = sf:::aggregate.sf(world["pop"], by = list(world$continent), FUN = sum, na.rm = TRUE)
```

works, but `?sf:::aggregate.sf` does not lead to the help file.

Seems that I better read Hadley's chapter on generic methods (thank you for the link).

As far as the wording goes, I actually find the initial wording quite clear (once the typo is corrected to `sf:::aggregate.sf`). How would you feel about this:

> `aggregate()` is a generic function which means that it behaves differently depending on its inputs. **sf** provides the method `aggregate.sf` which is activated automatically when a `by` argument is provided, rather than using the `~` to refer to the grouping variable:`

**Comment by prosoitos** [comment]
I pushed a new commit with a wording suggestion. Let me know whether this seems clear.

Thanks!

**Comment by Robinlovelace** [comment]
Looks good. Only change I'd recommend based on the latest version is mentioning that `x` must be an `sf` object. How would this be:

```
aggregate()` is a generic function which means that it behaves differently depending on its inputs. **sf** provides the method `aggregate.sf()` which is activated automatically when `x` is an `sf` object and a `by` argument is provided:
````

I think mentioning `~` could confuse people, so removed in this suggestion. Thanks for raising this.

**Comment by prosoitos** [comment]
Looks good to me. I will push the change.

**Comment by prosoitos** [comment]
I also added a link to Hadley's chapter on generics as I personally found it useful to understand this. But I am happy to rebase this last commit if you don't like the link.

**Comment by Nowosad** [comment]
Nice changes! Thanks.

**Pull request merged**
