### PR TITLE
Discord and branch renaming

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Nowosad** [comment]
@Robinlovelace I think you also need to rerender README.md

**Comment by Robinlovelace** [comment]
README.md has been updated.

**Comment by Robinlovelace** [comment]
There were more changes needed than expected but think this is good to go. Review + merge v. welcome @Nowosad, on Discord for chat also...

**Review by Nowosad — APPROVED** [review]
Everything seems ok

**Pull request merged**
