### PR TITLE
Ghactions

### PR DESCRIPTION
**Pull request by Nowosad**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Great work @Nowosad let me know if you want me to take a look at any point.

**Comment by Nowosad** [comment]
Will do - I am getting closer to the solution.

**Comment by Nowosad** [comment]
@Robinlovelace see https://github.com/Robinlovelace/geocompr/runs/576951334?check_suite_focus=true

**Comment by Robinlovelace** [comment]
I think this is good to go, Netlify auto-deploys from the `gh-pages` branch so I don't think we need that action, the only one failing by the looks of it.

**Comment by Nowosad** [comment]
So feel free to merge. We can deal with the second workflow later.

**Pull request merged**
