### PR TITLE
Try to fix language misclassification

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
After this commit it is classified correctly as an R project:

```
github-linguist .                                     
64.86%  R
32.90%  TeX
1.01%   Dockerfile
0.68%   CSS
0.21%   Rebol
0.17%   Makefile
0.17%   Shell

```

**Comment by Robinlovelace** [comment]
And after that latest change to .gitattributes:

```
github-linguist .                                     
81.98%  R
15.20%  TeX
1.28%   Dockerfile
0.86%   CSS
0.26%   Rebol
0.21%   Makefile
0.21%   Shell

```

**Comment by Robinlovelace** [comment]
@Nowosad not but this will not affect the LaTeX version as shown here: https://github.com/Robinlovelace/geocompr/pull/471/files#diff-22c8367d5e418a8bb57816a95687457cR613-R621

**Comment by Nowosad** [comment]
Thanks! I missed those lines of code above.

**Pull request merged**
