### PR TITLE
chapter 13 : adding Docker as fourth solution for parallelized computing under Windows

### PR DESCRIPTION
**Pull request by pokyah**
Hi !
Useful book to me as I'm beginning to build a weather app providing spatialized weather data under R ! 
 
Docker might also be an efficient solution for Windows users as it allows to quickly configure and run an Unix based-OS with a precise set of software version and dependencies. If you want to know more, you can check my [tutorial](https://pokyah.github.io/howto/using-r-with-docker/) about using R with docker .

Thanks for reviewing

### CODE REVIEW

**Comment by Robinlovelace** [comment]
This looks good to me, thanks for the input @pokyah. Will leave it for @Nowosad and @jannes-m and comment / merge.

**Comment by jannes-m** [comment]
Yes, you are right, this is another viable solution!

**Comment by pokyah** [comment]
You are welcome !

**Comment by znmeb** [comment]
A couple of cautions on Docker for Windows:

1. There are two versions of Docker that run on Windows - Docker for Windows and the older Docker Toolbox. Docker for Windows requires Windows 10 Pro - no other version of Windows is supported. If you have any other version of Windows, you need Docker Toolbox.
2. In either case, Docker operates inside a full virtual machine running Linux. Thus it has available at most half of the RAM in your desktop / laptop, and often less than half. For example, my Windows 10 Pro laptop has 8 GB of RAM, but by default Docker containers only have 2 GB to work with. I've been able to push it up to 3 GB but not to 4.

Because of the virtual machine. there is also a measurable processor overhead associated with Docker on a Windows host. I don't know what the exact tradeoffs are, but I recommend running native tools on Windows whenever possible.

**Comment by jannes-m** [comment]
@znmeb You are perfectly right. In terms of parallelization it does not make too much sense but at least you could run the code. In any case, I will probably rewrite the corresponding paragraph by providing also an example how to parallelize the code on a Windows machine (but then without `mc.set.seed`).

**Comment by znmeb** [comment]
@jannes-m Isn't there a parallel random number generator on Windows? It's been a long time since I used Windows R.

**Pull request merged**
