### PR TITLE
Update 04-spatial-operations.Rmd

### PR DESCRIPTION
**Pull request by MikeJohnPage**
Added missing 'and'.

### CODE REVIEW

**Review by Robinlovelace — COMMENTED** [review]
I think the original text is fine. Remove the clause in commas and it reads:

> All spatial objects are related through space and distance calculations can be used to explore the strength of this relationship.

Would the section be better as:

> All spatial objects are related through space, and distance calculations can be used to explore the strength of this relationship. These are covered in Section xx.

?

**Comment by MikeJohnPage** [comment]
Ah, having read your second suggestion I understand where the misunderstanding has happened. I read the original quote like this (notice the added comma):

> All spatial objects are related through space and distance, calculations can be used to explore the strength of this relationship.

I just showed the original text to a peer and they made the same mistake. Perhaps your second suggestion is better in this case?

> All spatial objects are related through space, and distance calculations can be used to explore the strength of this relationship. These are covered in Section xx.

**Comment by Robinlovelace** [comment]
> Perhaps your second suggestion is better in this case?

I agree. Could you update the Pull Request?

Thanks for flagging this, always room for improvement.

**Comment by MikeJohnPage** [comment]
> Thanks for flagging this, always room for improvement.

No problem, thanks for writing a great resource

> Could you update the Pull Request?

Done 👍

**Review by Robinlovelace — APPROVED** [review]

**Pull request merged**
