### PR TITLE
Add draft intro to CLI/GUI chapter

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Nowosad** [comment]
@Robinlovelace should we merged this pull request?

**Comment by Robinlovelace** [comment]
Up to you - was put there as an example of what this could look like, I see no harm in merging it for now. @jannes-m and @pat-s would you be happy with this and PR into the master branch? If so I say merge this.

**Comment by pat-s** [comment]
Sure, merge this ;)

Also have a look at https://github.com/gisma/link2GI and https://speakerdeck.com/pat_s/r-als-gis. Unfortunately, the latter is in German but maybe you can get something out of it by looking at the code examples.

**Comment by Nowosad** [comment]
@pat-s Thanks, Patrick. Looks interesting.

**Pull request merged**
