### PR TITLE
Update 11-gis.Rmd

### PR DESCRIPTION
**Pull request by gisma**
Updated link2GI on CRAN so it will produce no error calling rsaga.env Nevertheless RSAGA and link2GI is only connected on getting the correct installation pathes and not setting the environment Vars so you have to call it with the correct pathes.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Many thanks @gisma - I was having issues running this on my own Ubuntu computer, let alone on Travis so changes such as these very much appreciated. Will leave it to the main chapter author @jannes-m to merge / comment if needs be. Overall: 👍 from me.

**Comment by Robinlovelace** [comment]
You happy with this @jannes-m ? and the other PR on the GIS chapter.

**Comment by jannes-m** [comment]
I guess so, But I will have to try it. So far, I haven't run the code. In any case, thanks @gisma!

**Comment by jannes-m** [comment]
@gisma can you pls sync your branch with the master branch so that we can merge (I guess this is because 11-gis.Rmd was renamed to 10-gis.Rmd)

**Comment by gisma** [comment]
I do not like it but I'm a bit overwhelmed with but with the for me common  `git fetch upstream master` and `git merge upstream / master` I see no updated version. Do I miss something? I could easily fork it again and create a new pull request. Probably the easiest way?

**Comment by Robinlovelace** [comment]
Woa yeah usually small changes are easy to deal with but in this case 'reforking' it may be the best option! Many thanks again for your contribution.

**Comment by gisma** [comment]
uuh need some help. I simply don't see the conflicting file `11-gis.Rmd` neither in one of your branches nor (of course) in the fork

**Comment by Robinlovelace** [comment]
I think this is it and it looks like @jannes-m has already integrated your suggestions in this commit https://github.com/Robinlovelace/geocompr/commit/738297be13d3917820be99788e44259281f6e4e8 - awesome work!

**Pull request closed without merging**
