### PR TITLE
'calcHistMatch()' was moved to 'satelliteTools'

### PR DESCRIPTION
**Pull request by patperu**
Little correction.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Thanks for this @patperu

**Comment by Robinlovelace** [comment]
Sounds like a good plan Jannes.

**Comment by patperu** [comment]
Oh yes, good point! So, you will find a solution, right?
BTW I found this function because I was looking for a way to replicate this analysis [https://github.com/vis4/eu-drought](https://github.com/vis4/eu-drought) with R.

**Comment by Robinlovelace** [comment]
Worth contacting the package developers to see what they recommend?

**Comment by Robinlovelace** [comment]
Any update on this @patperu ? Looking at it it seems the package hasn't changed but I don't want the book to be out-of-date.

**Comment by Robinlovelace** [comment]
What do you think @Nowosad and @jannes-m ?

**Comment by jannes-m** [comment]
The correction is correct. Unfortunately, package **satelliteTools** is only available on [github](https://github.com/environmentalinformatics-marburg/satelliteTools/tree/master/R). So there are three options:

1. say in the text, that **satelliteTools** is only available on github
1. delete the reference to **satelliteTools**
1. say in a footnote that there is another option available in a github package

**Comment by Robinlovelace** [comment]
Thanks @jannes-m, I think all 3 options sound viable. This sounds the simplest:

> say in the text, that satelliteTools is only available on github

**Comment by Robinlovelace** [comment]
Superseded by https://github.com/Robinlovelace/geocompr/commit/f918610935350a726e1d71f7f36c0f4eab92dd88

**Pull request closed without merging**
