### PR TITLE
Remove existing giant files (to test build) - see #202

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Good to merge @jannes-m and @Nowosad ? Note `spatialcv.Rdata` is still there but is a fair bit smaller as illustrated here:

```bash
ls -hal extdata/spatialcv.Rdata
# -rw-rw-r-- 1 robin robin 1.2M Apr 19 16:08 extdata/spatialcv.Rdata
git checkout master
# Switched to branch 'master'
# Your branch is up-to-date with 'origin/master'.
ls -hal extdata/spatialcv.Rdata
# -rw-rw-r-- 1 robin robin 4.8M Apr 19 16:08 extdata/spatialcv.Rdata
```

**Comment by Robinlovelace** [comment]
Only task left now: convert `spatialcv.Rdata` into `extdata/conv_cv.rds` and `extdata/sp_cv.rds` then we can purge all the giant binaries for once and for all (I think). You up for doing that @jannes-m?

**Comment by Robinlovelace** [comment]
See #202

**Comment by jannes-m** [comment]
Ok, I have changed that but will wait with pushing until Jakub accepted my **spDataLarge** PR to avoid breaking the build.

**Comment by Robinlovelace** [comment]
Awesome work, many thanks!

**Comment by Nowosad** [comment]
**spDataLarge** should be updated now.

**Pull request merged**
