### PR TITLE
rstudio/bookdown

### PR DESCRIPTION
**Pull request by Nowosad**
Test to make footnotes work.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
I'll try clearing the cache and rebuilding.

**Comment by Nowosad** [comment]
If that is possible - then this is probably a better move.

**Comment by Robinlovelace** [comment]
Seems harder than expected: https://github.community/t5/GitHub-Actions/Web-interface-to-browse-and-delete-cache-entries-feature-request/td-p/47858

**Comment by Robinlovelace** [comment]
Seems to be using CRAN version of `tmaptools`, again: 

```
2020-04-22T10:19:58.2943485Z tmaptools    (adbf1da21... -> 3.0         ) [CRAN]
```

I will merge and see what happens...

**Pull request merged**
