### PR TITLE
Issue446

### PR DESCRIPTION
**Pull request by dcooley**
`sfheaders.Rmd` for #466 

The Rmd includes all the core concepts and examples of what the library is about and how to use it. I didn't think it was worth going over the top and adding examples of each individual function. But if you want it fleshed out a bit let me know.

Otherwise I'm happy for you to take this, edit it and insert it into the appropriate chapter of the book.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Many thanks @dcooley, this looks like a great intro to the fantastic `sfheaders` package. I will look to integrate this into the main text ASAP. One thought: a big advantage of `sfheaders` is speed so could include a benchmark... I think the C++ code may be too advanced for this book but worthy of flagging in the text and maybe with reference to this https://dcooley.github.io/sfheaders/articles/Cpp.html

**Comment by dcooley** [comment]
> so could include a benchmark

yes that's a good idea. 

> I think the C++ code may be too advanced for this book but worthy of flagging in the text and maybe with reference to this

Fair point; I'll remove that chunk of text, but mention it's _possible, but out of scope for the book_.

**Comment by Robinlovelace** [comment]
> Fair point; I'll remove that chunk of text, but mention it's _possible, but out of scope for the book_.

Sounds good. Also, I'm up for making the tidy-up changes and integrating the text. You've done the hard work (not least by creating the amazing `sfheaders` package which needs more attention)!

**Comment by Robinlovelace** [comment]
OK. On the case...

**Comment by Robinlovelace** [comment]
Heads-up @dcooley I'm seeing this error message on the final line:

``` r
n = 4
df = data.frame(
  x = 1:n
  , y = n:1
)
sfheaders::sfg_polygon(obj = df)
#> [[1]]
#>      [,1] [,2]
#> [1,]    1    4
#> [2,]    2    3
#> [3,]    3    2
#> [4,]    4    1
#> [5,]    1    4
#> 
#> attr(,"class")
#> [1] "XY"      "POLYGON" "sfg"
sf <- sfheaders::sfg_polygon(obj = df)
sf::st_crs(sf) <- 4326  ## Web Mecarter (long/lat)
#> Error in UseMethod("st_crs<-"): no applicable method for 'st_crs<-' applied to an object of class "c('XY', 'POLYGON', 'sfg')"
```

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dcooley** [comment]
`sfg`'s don't have CRS ?

**Comment by dcooley** [comment]
```r
sf <- sf::st_point(1:2)
sf::st_crs(sf) <- 4326  ## Web Mecarter (long/lat)
```

**Comment by Robinlovelace** [comment]
Heads-up, here's a WIP port of your text into the main body of the book: https://github.com/Robinlovelace/geocompr/pull/741

**Comment by dcooley** [comment]
nice. Do you still want me to add a benchmark, or are you doing that?

**Comment by Robinlovelace** [comment]
> nice. Do you still want me to add a benchmark, or are you doing that?

I can give it a go. May ask for your review.

**Comment by dcooley** [comment]
Of course

**Comment by Robinlovelace** [comment]
Superceded by #741. Commits in this PR: merged :rocket:

**Pull request closed without merging**
