### PR TITLE
Update Geomarketing chapter

### PR DESCRIPTION
**Pull request by jannes-m**

### CODE REVIEW

**Comment by jannes-m** [comment]
This PR is good to go. Before merging it, we should merge first https://github.com/Nowosad/spDataLarge/pull/35 otherwise the CI will fail. Equally, we should merge https://github.com/geocompr/geocompkg/pull/39 since it removes the no longer needed **revgeo** dependency.

**Comment by Nowosad** [comment]
Thanks @jannes-m -- I skimmed the text and it looks good. I will merge it now and review it  soon.

**Comment by jannes-m** [comment]
Excellent, thanks!!

**Comment by Robinlovelace** [comment]
+ deleting the branch :+1:

**Comment by jannes-m** [comment]
thanks, Robin, I should have deleted the branch myself

**Pull request merged**
